from __future__ import annotations

from datetime import date
from decimal import Decimal
from typing import Any, Protocol

from guardian.domain.models import Balance, Candle, OrderRequest, OrderResult, RiskSnapshot, Signal


class OrderExecutionUnknown(RuntimeError):
    """The exchange may have accepted an order, but its final state is not yet provable."""

    def __init__(self, client_order_id: str, message: str) -> None:
        super().__init__(message)
        self.client_order_id = client_order_id


class ExchangePort(Protocol):
    async def ping(self) -> None: ...
    async def server_time_ms(self) -> int: ...
    async def symbol_info(self, symbol: str) -> dict[str, Any]: ...

    async def candles(self, symbol: str, interval: str,
                      limit: int) -> list[Candle]: ...
    async def historical_candles(
        self, symbol: str, interval: str, limit: int) -> list[Candle]: ...

    async def price(self, symbol: str) -> Decimal: ...
    async def balance(self, base_asset: str, quote_asset: str) -> Balance: ...

    async def place_market_order(
        self, request: OrderRequest) -> OrderResult: ...

    async def find_order(
        self, request: OrderRequest) -> OrderResult | None: ...

    async def place_protective_stop(
        self, symbol: str, quantity: Decimal, stop_price: Decimal, limit_price: Decimal
    ) -> dict[str, Any] | None: ...


class TradingRepository(Protocol):
    def initialize(self) -> None: ...

    def record_order(self, order: OrderResult,
                     realized_pnl: Decimal | None = None) -> bool: ...

    def record_order_with_state(
        self, order: OrderResult, state: dict[str, str], realized_pnl: Decimal | None = None
    ) -> bool: ...
    def list_orders(self, limit: int = 100) -> list[dict[str, object]]: ...

    def risk_snapshot(
        self, day: date, current_price: Decimal, timezone_name: str = "UTC"
    ) -> RiskSnapshot: ...
    def set_state(self, key: str, value: str) -> None: ...
    def set_states(self, values: dict[str, str]) -> None: ...
    def get_state(self, key: str, default: str = "") -> str: ...

    def record_observation(
        self, symbol: str, interval: str, candle: Candle, signal: Signal
    ) -> None: ...
    def observation_count(self) -> int: ...
    def save_training_result(self, result: dict[str, object]) -> None: ...
    def latest_training_result(self) -> dict[str, object] | None: ...
    def create_shadow_model(
        self, model: dict[str, object], starting_quote: Decimal) -> bool: ...

    def deactivate_shadow_family(self, strategy: str) -> None: ...
    def deactivate_shadow_slot(self, strategy: str, interval: str) -> None: ...

    def list_shadow_models(
        self, active_only: bool = True) -> list[dict[str, object]]: ...

    def update_shadow_model(self, model_id: str,
                            state: dict[str, object]) -> None: ...

    def record_shadow_trade(
        self, trade: dict[str, object], state: dict[str, object] | None = None
    ) -> None: ...
    def list_shadow_trades(
        self, limit: int = 100) -> list[dict[str, object]]: ...

    def shadow_performance(self) -> list[dict[str, object]]: ...

    def record_shadow_equity(
        self,
        model_id: str,
        sample_time: str,
        equity: Decimal,
        price: Decimal,
        in_position: bool,
    ) -> None: ...

    def record_event(
        self, event_type: str, message: str, level: str = "INFO", details: dict | None = None
    ) -> None: ...
    def list_events(self, limit: int = 100) -> list[dict[str, object]]: ...
    def record_equity(self, equity: Decimal, price: Decimal) -> None: ...
    def performance_summary(self) -> dict[str, object]: ...
